name: emowall
description: Emowall Pro - Premium Crypto & Staking Tracker
version: 1.0.6+106
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.0.2
  flutter_secure_storage: ^10.0.0
  local_auth: ^3.0.1
  http: ^1.2.1
  connectivity_plus: ^7.0.0
  flutter_local_notifications: ^20.1.0
  sensors_plus: ^7.0.0
  audioplayers: ^6.0.0
  url_launcher: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/ai_alert.mp3
    - assets/sounds/baby_cry.mp3
    - assets/sounds/baby_song.mp3
